### ISSUE TITLE
Notifications says task added, but tasks not creating 

### ISSUE THREAD

**Issue by spellanser** [idpaterson/alfred-wunderlist-workflow#101]
Alfred v2.8.2, latest workflow. Issue appears for all lists, including inbox. 
No matter how many properties is set in process of task creation.

**Comment by idpaterson** [comment]
Would you then please try signing out of the workflow at `wl:pref` then signing back in to see if there may be a permission issue? In case the problem persists I am going to post a test version of the workflow here that will log the network activity to Alfred's console to more clearly identify the error.

**Comment by idpaterson** [comment]
If you are still having trouble, please [install the attached workflow](https://github.com/idpaterson/alfred-wunderlist-workflow/files/154850/Wunderlist-test-task-networking.alfredworkflow.zip) then click the bug icon in Alfred on the Wunderlist workflow screen to open the workflow log and change the dropdown from *Interesting information* to *All information*. Next, run `wl test` in Alfred to add a simple task to your Inbox. If it works correctly, try a more complicated task with list, due date, and recurrence.

You will see something like the following at the bottom of the workflow log. Please paste the request and response headers as shown, obscuring the `x-access-token` and `X-Current-User-ID` values:
```
[INFO: alfred.workflow.action.script] Processing output 'alfred.workflow.output.notification' with arg 'send: 'POST /api/v1/tasks HTTP/1.1\r\nHost: a.wunderlist.com\r\nContent-Length: 77\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nUser-Agent: python-requests/2.7.0 CPython/2.7.10 Darwin/15.3.0\r\nConnection: keep-alive\r\nx-client-id: ca5911eefc34faa969a4\r\nx-access-token: *****************\r\ncontent-type: application/json\r\n\r\n{"starred": false, "title": "test", "completed": false, "list_id": 105296032}'
reply: 'HTTP/1.1 201 Created\r\n'
header: Cache-Control: max-age=0, private, must-revalidate
header: Content-Type: application/json
header: Date: Wed, 02 Mar 2016 13:21:00 GMT
header: Server: nginx
header: X-Current-User-ID: **********
header: X-Request-ID: 5c45d77e-4874-4954-aca3-3eb500f87129-4860
header: Content-Length: 177
header: Connection: keep-alive
```

**Comment by idpaterson** [comment]
I just experienced potentially the same issue when trying to add a task. The Wunderlist API reported a 500 internal server error so I checked the request with curl and noticed that it was sending `list_id: 0`. Furthermore, my lists were not showing up in the workflow. My lists are in the SQLite database, but it looks like they might not be cached properly. In order to keep task parsing quick the lists are supposed to be cached to a file.

I believe that this particular problem should only affect the alpha versions. @spellanser were you using an alpha or production version of the workflow?

**Comment by idpaterson** [comment]
Actually this is looking more like an issue with alfred-workflow... debugging shows that the data is attempting to be stored, but the file is not created. In that case, it will also affect the latest production version.

**Comment by idpaterson** [comment]
This was not an issue with alfred-workflow, just how I was using it. In switching the sync to a multi-threaded process I did not realize that stored data is not supported across multiple threads. I can work around this problem for the next alpha update; it should not affect the 0.5.x production releases.

**Comment by spellanser** [comment]
Sorry for long time answer, wl:pref with logout fix issue for me. 
Thank you for your support!
