### ISSUE TITLE
How to change the default list?

### ISSUE THREAD

**Issue by manavortex** [idpaterson/alfred-wunderlist-workflow#103]
Hey there, 
I'm a terribly lazy person, and I would love to change the default list from inbox to my shopping list. How can this be done?  (I wouldn't mind messing with the source code for this, if you point me to the right direction)

Apart from that, amazing work(flow), love the look'n'feel.

**Comment by idpaterson** [comment]
That's a great idea! It's certainly no trouble to add a preference to change the default list, you can expect to see it in an upcoming 0.6.0 pre-release.

**Comment by manavortex** [comment]
Awesome, can't wait :D

**Comment by idpaterson** [comment]
I need to do a bit more testing but the default list preference will definitely be in the next pre-release.

![preference](https://cloud.githubusercontent.com/assets/507058/13731121/1e970ffa-e938-11e5-8505-31e79a48f569.png)

![task](https://cloud.githubusercontent.com/assets/507058/13731124/24e4bd44-e938-11e5-965f-4bab72af51a9.png)

**Comment by manavortex** [comment]
Awesome! I'll volunteer for the testing. :D

**Comment by idpaterson** [comment]
Check out [0.6.0-alpha.6](https://github.com/idpaterson/alfred-wunderlist-workflow/releases/tag/0.6.0-alpha.6)

**Comment by manavortex** [comment]
Hey there, 
![screen shot 2016-03-17 at 11 19 29](https://cloud.githubusercontent.com/assets/965785/13843132/332b4b50-ec32-11e5-8c92-17eda91b8201.png)

Will try reinstalling :)

**Comment by idpaterson** [comment]
I think the only "query" on the `wl-pref` screen is to get the current user record. If the database had to be wiped out (e.g. just logged in, or you previously had 0.5.x installed and DB was wiped) it will take a few moments for the first sync to pick up your user record. The User is the first thing synced so from what I've seen this error should only happen for a short time (like 10 seconds after the sync). Let me know what you find

**Comment by manavortex** [comment]
Ah, alright!

The error had me concerned. :)
