### ISSUE TITLE
How to view my list?

### ISSUE THREAD

**Issue by gfxcc** [idpaterson/alfred-wunderlist-workflow#104]
as title.
This is a great workflow.
Thanks

**Comment by idpaterson** [comment]
This is coming in version 0.6.0 (assuming that you mean viewing all of the tasks in a list). You can download the pre-release now or update your workflow preference to automatically get notified when a pre-release update is available. So far in 0.6.0 you can search tasks and view what's due.

**Comment by gfxcc** [comment]
Thanks for your reply. Looking forward to that.

**Comment by idpaterson** [comment]
Does this work for what you need? I am adding lists to the search in 0.6.0 to make it a search/browse:

### Default search view
![search](https://cloud.githubusercontent.com/assets/507058/13865572/12bbe306-ec83-11e5-9993-0352a6bb5178.png)

### Filter lists
![filter](https://cloud.githubusercontent.com/assets/507058/13865580/25d21a78-ec83-11e5-8ec4-fc16d24bd538.png)

### View a list
![view list](https://cloud.githubusercontent.com/assets/507058/13865584/3023b66c-ec83-11e5-936c-45950ed8bf4d.png)

### Search within a list
![search list](https://cloud.githubusercontent.com/assets/507058/13865587/3bba2696-ec83-11e5-990f-890cb6eba9d1.png)

### Search all lists
![search](https://cloud.githubusercontent.com/assets/507058/13865628/a6fe572e-ec83-11e5-9d4f-4362178787bc.png)

**Comment by idpaterson** [comment]
This has been released in [0.6.0-alpha.7](https://github.com/idpaterson/alfred-wunderlist-workflow/releases/tag/0.6.0-alpha.7)
