### ISSUE TITLE
Workflow infinitely in preparing state

### ISSUE THREAD

**Issue by spellanser** [idpaterson/alfred-wunderlist-workflow#114]
http://imgur.com/xOSDF21
System reboot, workflow reinstall doesn't solve the problem.

**Comment by idpaterson** [comment]
Please try deleting the file at `~/Library/Application\ Support/Alfred\ 2/Workflow\ Data/com.ipaterson.alfred.wunderlist/settings.json.lock` if it exists. If so, *very important*, please respond with the version number of your workflow shown at `wl:about`. This is a problem that should have been fixed but if not I need to investigate other causes.

If that does not seem to be the problem, show me `ls ~/Library/Application\ Support/Alfred\ 2/Workflow\ Data/com.ipaterson.alfred.wunderlist/` and let's continue to debug.

**Comment by IanVS** [comment]
Upgrading to 0.5.4 and removing the file you mentioned solved this problem for me.  Thanks!

**Comment by idpaterson** [comment]
That is good news!

**Comment by spellanser** [comment]
Thank you very much, this solution really solves the problem.
