### ISSUE TITLE
Error on entering "wl", "Unable to run task!"

### ISSUE THREAD

**Issue by superfunkminister** [idpaterson/alfred-wunderlist-workflow#121]
As soon as I type "wl" I get the following popup...
![ember error popup](https://cloud.githubusercontent.com/assets/1285419/15564067/1639960e-2306-11e6-8dac-0833653af47a.png)

**Comment by idpaterson** [comment]
This error [seems to suggest](http://www.alfredforum.com/topic/3598-workflow-unable-to-run-task/) that one of the executables that Alfred is relying on for running scripts in the workflow is missing. Please run the following in your Terminal and paste back the results so that I can see if anything is abnormal:
```bash
ls /bin/bash; which bash; /bin/bash --version; ls /usr/bin/env; ls /usr/bin/python; which python; /usr/bin/env python --version
```

**Comment by superfunkminister** [comment]
Weirdly uninstalling it and reinstalling it led to a broken workflow, however uninstalling it, restarting then reinstalling seems to make it work.

Here's the output for reference anyway:

``` sh
/bin/bash
/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
/usr/bin/env
/usr/bin/python
/usr/bin/python
Python 2.7.10
```

**Comment by idpaterson** [comment]
Thanks, that is quite strange. I haven't seen that error before and the only discussion that I could find suggested that the executable used to run the workflow was missing (in the case of this workflow that would be bash, which I think would be extremely unlikely). Which version of the workflow and of Alfred are you using just in case anyone else has this problem?

**Comment by superfunkminister** [comment]
Ah yes, I'm on Alfred 3 using 0.5.4 of the workflow. Cheers nonetheless!
