### ISSUE TITLE
Due does not work in beta 0.6.0-beta.3

### ISSUE THREAD

**Issue by csteinlehner** [idpaterson/alfred-wunderlist-workflow#122]
Hi,

if I type "wl clean next wednesday" I get a task named "clean next wednesday" without a due date. Is this feature broken or am I using it wrong?

Thanks!

**Comment by idpaterson** [comment]
Is your system locale German or another non-English language? The workflow may be expecting German input like `nächster Mittwoch`. I recall intending to add a setting to always use English since I can't necessarily document examples in all supported languages.

**Comment by csteinlehner** [comment]
Ah yes, I got a german system. Works perfect, thanks. What's the underlying technology?

**Comment by idpaterson** [comment]
The workflow uses [parsedatetime](https://github.com/bear/parsedatetime) for natural language date processing. I am a contributor on that project as well and [started to improve the German translations](https://github.com/bear/parsedatetime/issues/102) last year with the help of Wunderlist workflow user @ckoeberle. There were quite a few challenges there and it proved difficult to write meaningful test cases without knowing the language. If you notice any issues or are interested in improving parsedatetime by helping out with those date and time phrase test cases just let me know!
