### ISSUE TITLE
Can't connect to localhost:6200

### ISSUE THREAD

**Issue by johnbent** [idpaterson/alfred-wunderlist-workflow#126]
I saw there was another closed issue about this:
https://github.com/idpaterson/alfred-wunderlist-workflow/issues/54
But I'm still seeing it now.
wunderlist 3.4.4 (40)
alfred 3.0.2 (676)
python 2.7.10

I tried running the python and it seems to work but then I'm still not authorized.  Here's the python output:

`Workflow version : 0.6.0-beta.4
The debug log can be found in the log file:
/Users/john.bent/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.ipaterson.alfred.wunderlist/com.ipaterson.alfred.wunderlist.log
2016-06-28 10:35:42,565 workflow     DEBUG    Command arguments cached to `/Users/john.bent/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.ipaterson.alfred.wunderlist/sync.argcache`
2016-06-28 10:35:42,566 workflow     DEBUG    Calling [u'/usr/bin/python', '/Users/john.bent/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.7F5CD591-5B72-4846-A910-A9FBEC0B0567/workflow/background.pyc', 'sync'] ...
The debug log can be found in the log file:
/Users/john.bent/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.ipaterson.alfred.wunderlist/com.ipaterson.alfred.wunderlist.log
Workflow finished in 0.010 seconds.
Workflow finished in 0.013 seconds.
2016-06-28 10:35:42,683 workflow     DEBUG    Executing task `sync` in background...
2016-06-28 10:35:42,684 wunderlist   INFO     Workflow response complete
2016-06-28 10:35:42,684 workflow     DEBUG    Set last run version : 0.6.0-beta.4
2016-06-28 10:35:42,684 workflow     DEBUG    Workflow finished in 0.174 seconds.
Workflow finished in 0.174 seconds.
`

Here's the debug log:

`10:28:09 workflow.py:1666 DEBUG    No data stored for `prefs`
10:28:09 workflow.py:2154 DEBUG    Workflow version : 0.5.4
10:28:09 workflow.py:1557 DEBUG    Reading settings from `/Users/john.bent/Library/Application Support/Alfred 2/Workflow Data/com.ipaterson.alfred.wunderlist/settings.json` ...
10:28:09 workflow.py:1557 DEBUG    Reading settings from `/Users/john.bent/Library/Application Support/Alfred 2/Workflow Data/com.ipaterson.alfred.wunderlist/settings.json` ...
10:28:09 workflow.py:2428 INFO     Checking for update ...
10:28:09 background.py:188 DEBUG    Command arguments cached to `/Users/john.bent/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.ipaterson.alfred.wunderlist/__workflow_update_check.argcache`
10:28:09 background.py:192 DEBUG    Calling [u'/usr/bin/python', '/Users/john.bent/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.7F5CD591-5B72-4846-A910-A9FBEC0B0567/workflow/background.py', u'__workflow_update_check'] ...
10:28:09 workflow.py:2190 DEBUG    Workflow finished in 0.014 seconds.
10:28:09 background.py:236 DEBUG    Task `__workflow_update_check` running
10:28:09 workflow.py:2190 DEBUG    Workflow finished in 0.029 seconds.
10:28:09 background.py:197 DEBUG    Executing task `__workflow_update_check` in background...
10:28:09 background.py:237 DEBUG    cmd : [u'/usr/bin/python', '/Users/john.bent/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.7F5CD591-5B72-4846-A910-A9FBEC0B0567/workflow/update.py', u'check', 'idpaterson/alfred-wunderlist-workflow', '0.5.4']
10:28:10 workflow.py:1666 DEBUG    No data stored for `auth`
10:28:10 workflow.py:1766 DEBUG    Stored data saved at : /Users/john.bent/Library/Application Support/Alfred 2/Workflow Data/com.ipaterson.alfred.wunderlist/auth.cpickle
10:28:10 workflow.py:2506 DEBUG    Password exists : com.ipaterson.alfred.wunderlist:oauth_state
10:28:10 update.py:233 DEBUG    Retrieving releases list from `https://api.github.com/repos/idpaterson/alfred-wunderlist-workflow/releases` ...
10:28:10 update.py:237 INFO     Retrieving releases for `idpaterson/alfred-wunderlist-workflow` ...
10:28:11 workflow.py:1828 DEBUG    Cached data saved at : /Users/john.bent/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.ipaterson.alfred.wunderlist/gh-releases-idpaterson-alfred-wunderlist-workflow.cpickle
10:28:11 update.py:254 WARNING  Invalid release 0.6.0-beta.4 : pre-release detected
10:28:11 update.py:254 WARNING  Invalid release 0.6.0-beta.3 : pre-release detected
10:28:11 update.py:254 WARNING  Invalid release 0.6.0-beta.2 : pre-release detected
10:28:11 update.py:254 WARNING  Invalid release 0.6.0-beta.1 : pre-release detected
10:28:11 update.py:254 WARNING  Invalid release 0.6.0-alpha.7 : pre-release detected
10:28:11 update.py:254 WARNING  Invalid release 0.6.0-alpha.6 : pre-release detected
10:28:11 update.py:265 DEBUG    Release `0.5.4` : https://github.com/idpaterson/alfred-wunderlist-workflow/releases/download/0.5.4/Wunderlist.alfredworkflow
10:28:11 update.py:254 WARNING  Invalid release 0.6.0-alpha.5 : pre-release detected
10:28:11 update.py:254 WARNING  Invalid release 0.6.0-alpha.4 : pre-release detected
10:28:11 update.py:254 WARNING  Invalid release 0.6.0-alpha.3 : pre-release detected
10:28:11 update.py:265 DEBUG    Release `0.5.3` : https://github.com/idpaterson/alfred-wunderlist-workflow/releases/download/0.5.3/Wunderlist.alfredworkflow
10:28:11 update.py:254 WARNING  Invalid release 0.6.0-alpha.2 : pre-release detected
10:28:11 update.py:254 WARNING  Invalid release 0.6.0-alpha.1 : pre-release detected
10:28:11 update.py:265 DEBUG    Release `0.5.2` : https://github.com/idpaterson/alfred-wunderlist-workflow/releases/download/0.5.2/Wunderlist.alfredworkflow
10:28:11 update.py:265 DEBUG    Release `0.5.1` : https://github.com/idpaterson/alfred-wunderlist-workflow/releases/download/0.5.1/Wunderlist.alfredworkflow
10:28:11 update.py:265 DEBUG    Release `0.5.0` : https://github.com/idpaterson/alfred-wunderlist-workflow/releases/download/0.5.0/Wunderlist.alfredworkflow
10:28:11 update.py:254 WARNING  Invalid release 0.5.0-beta.2 : pre-release detected
10:28:11 update.py:254 WARNING  Invalid release 0.5.0-beta.1 : pre-release detected
10:28:11 update.py:265 DEBUG    Release `0.4.1` : https://github.com/idpaterson/alfred-wunderlist-workflow/releases/download/0.4.1/Wunderlist.alfredworkflow
10:28:11 update.py:265 DEBUG    Release `0.4.0` : https://github.com/idpaterson/alfred-wunderlist-workflow/releases/download/0.4.0/Wunderlist.alfredworkflow
10:28:11 update.py:254 WARNING  Invalid release 0.4.0-beta.4 : pre-release detected
10:28:11 update.py:254 WARNING  Invalid release 0.4.0-beta.3 : pre-release detected
10:28:11 update.py:254 WARNING  Invalid release 0.4.0-beta.2 : pre-release detected
10:28:11 update.py:254 WARNING  Invalid release 0.4.0-beta.1 : pre-release detected
10:28:11 update.py:265 DEBUG    Release `0.3` : https://github.com/idpaterson/alfred-wunderlist-workflow/releases/download/0.3/Wunderlist.alfredworkflow
10:28:11 update.py:265 DEBUG    Release `0.202` : https://github.com/idpaterson/alfred-wunderlist-workflow/releases/download/0.202/Wunderlist.alfredworkflow
10:28:11 update.py:265 DEBUG    Release `0.2` : https://github.com/idpaterson/alfred-wunderlist-workflow/releases/download/0.2/Wunderlist.alfredworkflow
10:28:11 update.py:254 WARNING  Invalid release 0.2-beta.3 : pre-release detected
10:28:11 update.py:254 WARNING  Invalid release 0.2-beta.2 : pre-release detected
10:28:11 update.py:254 WARNING  Invalid release 0.2-beta.1 : pre-release detected
10:28:11 update.py:293 INFO     10 releases for idpaterson/alfred-wunderlist-workflow
10:28:11 update.py:304 DEBUG    Latest : Version('0.5.4') Installed : Version('0.5.4')
10:28:11 workflow.py:1828 DEBUG    Cached data saved at : /Users/john.bent/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.ipaterson.alfred.wunderlist/__workflow_update_status.cpickle
10:28:11 background.py:248 DEBUG    Task `__workflow_update_check` finished
10:28:11 workflow.py:2334 WARNING  Can't save last version: workflow has no version
10:28:11 workflow.py:2190 DEBUG    Workflow finished in 1.217 seconds.
10:31:34 workflow.py:2190 DEBUG    Workflow finished in 204.710 seconds.
10:31:47 background.py:188 DEBUG    Command arguments cached to `/Users/john.bent/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.ipaterson.alfred.wunderlist/sync.argcache`
10:31:47 background.py:192 DEBUG    Calling [u'/usr/bin/python', '/Users/john.bent/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.7F5CD591-5B72-4846-A910-A9FBEC0B0567/workflow/background.pyc', 'sync'] ...
10:31:47 workflow.py:2197 DEBUG    Workflow finished in 0.010 seconds.
10:31:47 background.py:236 DEBUG    Task `sync` running
10:31:47 workflow.py:2197 DEBUG    Workflow finished in 0.012 seconds.
10:31:47 background.py:237 DEBUG    cmd : ['/usr/bin/env', 'python', u'/Users/john.bent/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.7F5CD591-5B72-4846-A910-A9FBEC0B0567/alfred-wunderlist-workflow.py', 'pref sync', '--commit']
10:31:47 background.py:197 DEBUG    Executing task `sync` in background...
10:31:47 workflow.py:1556 DEBUG    Reading settings from `/Users/john.bent/Library/Application Support/Alfred 2/Workflow Data/com.ipaterson.alfred.wunderlist/settings.json` ...
10:31:47 workflow.py:2353 DEBUG    Set last run version : 0.6.0-beta.4
10:31:47 workflow.py:2197 DEBUG    Workflow finished in 0.196 seconds.
10:31:48 background.py:180 INFO     Task `sync` is already running
10:31:48 workflow.py:2353 DEBUG    Set last run version : 0.6.0-beta.4
10:31:48 workflow.py:2197 DEBUG    Workflow finished in 0.049 seconds.
10:31:48 background.py:248 DEBUG    Task `sync` finished
10:31:48 workflow.py:2342 WARNING  Can't save last version: workflow has no version
10:31:48 workflow.py:2197 DEBUG    Workflow finished in 0.443 seconds.
10:35:23 background.py:188 DEBUG    Command arguments cached to `/Users/john.bent/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.ipaterson.alfred.wunderlist/sync.argcache`
10:35:23 background.py:192 DEBUG    Calling [u'/usr/bin/python', '/Users/john.bent/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.7F5CD591-5B72-4846-A910-A9FBEC0B0567/workflow/background.pyc', 'sync'] ...
10:35:23 workflow.py:2197 DEBUG    Workflow finished in 0.010 seconds.
10:35:23 workflow.py:2197 DEBUG    Workflow finished in 0.011 seconds.
10:35:23 background.py:236 DEBUG    Task `sync` running
10:35:23 background.py:237 DEBUG    cmd : ['/usr/bin/env', 'python', u'/Users/john.bent/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.7F5CD591-5B72-4846-A910-A9FBEC0B0567/alfred-wunderlist-workflow.py', 'pref sync', '--commit']
10:35:23 background.py:197 DEBUG    Executing task `sync` in background...
10:35:23 workflow.py:2353 DEBUG    Set last run version : 0.6.0-beta.4
10:35:23 workflow.py:2197 DEBUG    Workflow finished in 0.187 seconds.
10:35:23 background.py:180 INFO     Task `sync` is already running
10:35:23 workflow.py:2353 DEBUG    Set last run version : 0.6.0-beta.4
10:35:23 workflow.py:2197 DEBUG    Workflow finished in 0.043 seconds.
10:35:23 background.py:248 DEBUG    Task `sync` finished
10:35:23 workflow.py:2342 WARNING  Can't save last version: workflow has no version
10:35:23 workflow.py:2197 DEBUG    Workflow finished in 0.428 seconds.
10:35:42 background.py:188 DEBUG    Command arguments cached to `/Users/john.bent/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.ipaterson.alfred.wunderlist/sync.argcache`
10:35:42 background.py:192 DEBUG    Calling [u'/usr/bin/python', '/Users/john.bent/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.7F5CD591-5B72-4846-A910-A9FBEC0B0567/workflow/background.pyc', 'sync'] ...
10:35:42 workflow.py:2197 DEBUG    Workflow finished in 0.010 seconds.
10:35:42 workflow.py:2197 DEBUG    Workflow finished in 0.013 seconds.
10:35:42 background.py:236 DEBUG    Task `sync` running
10:35:42 background.py:237 DEBUG    cmd : ['/usr/bin/env', 'python', u'/Users/john.bent/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.7F5CD591-5B72-4846-A910-A9FBEC0B0567/alfred-wunderlist-workflow.py', 'pref sync', '--commit']
10:35:42 background.py:197 DEBUG    Executing task `sync` in background...
10:35:42 workflow.py:2353 DEBUG    Set last run version : 0.6.0-beta.4
10:35:42 workflow.py:2197 DEBUG    Workflow finished in 0.174 seconds.
10:35:43 background.py:180 INFO     Task `sync` is already running
10:35:43 workflow.py:2353 DEBUG    Set last run version : 0.6.0-beta.4
10:35:43 workflow.py:2197 DEBUG    Workflow finished in 0.043 seconds.
10:35:43 background.py:248 DEBUG    Task `sync` finished
10:35:43 workflow.py:2342 WARNING  Can't save last version: workflow has no version
10:35:43 workflow.py:2197 DEBUG    Workflow finished in 0.412 seconds.
`

Thanks in advance for any help!

**Comment by idpaterson** [comment]
This can be a very system-dependent problem. Unfortunately Wunderlist does not allow me to use more than one port for the callback URL so if your machine is already using or in some way blocking port 6200 the authorization will not work. Since this is not something that can be resolved easily I added a workaround in #70.

Once you have logged in to Wunderlist your browser will try to load a URL beginning in `http://localhost:6200/`. In your case it sounds like the browser is showing a message that the URL cannot be loaded. The workaround is to simply paste that URL into the workflow's login help screen like `wl-help http://localhost:6200/?...` then press return.

Unfortunately it looks like I broke the help screen in the beta series, it should show some options here rather than the main menu. I'll get that fixed for you!
![screen shot 2016-06-28 at 12 49 54 pm](https://cloud.githubusercontent.com/assets/507058/16424599/d918da44-3d2e-11e6-9923-bd3c5d307f3e.png)

**Comment by idpaterson** [comment]
Please give [this version](https://github.com/idpaterson/alfred-wunderlist-workflow/raw/develop/Wunderlist.alfredworkflow) a try, I'll push out a formal fix later if this works for you.

You should be able to access a Help screen where you can paste the localhost URL:
![screen shot 2016-06-28 at 12 57 37 pm](https://cloud.githubusercontent.com/assets/507058/16424912/018041f6-3d30-11e6-8f9c-1783fea6a9f0.png)

**Comment by johnbent** [comment]
I'm using that new version (thanks!) but still can't get it working.  When
I tried pasting that url into the workflow login helpscreen, I get the
following:


​

**Comment by johnbent** [comment]
Sorry!  User error! I didn't paste the right URL following wl-help.  It now
works!  However, the window might need to be updated since it says Alfred 2
instead of Alfred 3:

Thanks!
​
