### ISSUE TITLE
Hashtag broken on create task in version 0.6.0-beta.6

### ISSUE THREAD

**Issue by csteinlehner** [idpaterson/alfred-wunderlist-workflow#129]
Hi, it looks like there is a bug if I want to add a new task with an hashtag. I attached a screenshot
<img width="611" alt="bildschirmfoto 2016-08-24 um 17 34 38" src="https://cloud.githubusercontent.com/assets/275506/17937146/7517d336-6a21-11e6-8340-b165d820904d.png">

**Comment by csteinlehner** [comment]
the new hashtag search gives me the same error.

**Comment by idpaterson** [comment]
Well that's not good. I made changes to the table and added some migration to make sure it would wipe out the old schema but apparently that did not happen in your case. Let me know if this continues after doing a `_wl-reset` in Alfred. It seems like there could be an error when recreating the database... do you see anything in the Alfred error log the first time you run the workflow after `_wl-reset`?

**Comment by csteinlehner** [comment]
with a _wl-reset everything works fine. with error log you mean the console, right? nothing interesting is there for alfred.

**Comment by idpaterson** [comment]
I see the same error after resetting but only until the initial sync finishes. I'll take a look at this later to at least avoid showing that error during the initial sync. Unless you're getting an error when the workflow is setting up the data it seems like something that should go away after the initial sync is complete.

**Comment by idpaterson** [comment]
Oh! I know what happened. This is going to affect everyone who downloads the new version so I'll patch it right away. 

The migration to the new database schema was performed, but the new "background" flag is not passed along when it re-syncs. When that migration occurs the sync ends up joining and waiting for its own process to finish (which never happens). I just need to maintain the background flag when resyncing after a schema migration.

**Comment by idpaterson** [comment]
The release is now patched. I will leave this open for a day or two in case anyone else downloaded the original version.
