### ISSUE TITLE
Task title format throws an error

### ISSUE THREAD

**Issue by tealiummike** [idpaterson/alfred-wunderlist-workflow#137]
I tried to create a task using the string

wl Morgtage Service Center 888-468-5671

And it does not create the task and throws a format error. I can't get to the exact error because it shows up on notifications. I am able to create the task using that string in the Wunderlist app directly.

**Comment by idpaterson** [comment]
@tealiummike thanks for reporting, please see #136. The Wunderlist API has been down all day and Wunderlist is [still working on it](https://status.wunderlist.com/).

**Comment by idpaterson** [comment]
@tealiummike can you try this again now? Wunderlist is back online. The Wunderlist desktop app continued to collect tasks locally but was not syncing over the past ~36 hours, so just double-check that any tasks added in the app are actually synced to Wunderlist now.
