### ISSUE TITLE
error message: sub() got an unexpected keyword argument 'flags'

### ISSUE THREAD

**Issue by beckgom** [idpaterson/alfred-wunderlist-workflow#138]
Hi all,

I got error message like below.

<img width="560" alt="2016-09-25 10 50 42 pm" src="https://cloud.githubusercontent.com/assets/5203242/18815690/bce1aace-8372-11e6-94f5-b83fb0ea96b5.png">

I think it is error message from python re package on 2.6.x version.
I have no idea because 2.7.10 is installed on my mac.

do you have any clue to fix it?

**Comment by idpaterson** [comment]
Sorry about that, I did not realize that Python 2.6 behaves differently here.

**Comment by idpaterson** [comment]
There were a few other minor changes ready to go out so I released [version 0.6.2](https://github.com/idpaterson/alfred-wunderlist-workflow/releases/tag/0.6.2) which should fix this for you.

**Comment by beckgom** [comment]
Super fast!! :)

It works well! Thank you
