### ISSUE TITLE
command "WL + task" does not add the task to my inbox

### ISSUE THREAD

**Issue by fabianvalkenberg** [idpaterson/alfred-wunderlist-workflow#142]
Hi,

Great fan of the workflow. I've been using it for several months now. Unfortunately it doesn't work anymore. When I use the command "WL + taskname" it does not add the task to my inbox. I do get the Mac notification that the task has been added but it does not appear in my inbox. 

On my iMac and Macbook I have the same issue. I have the latest release of your workflow and wunderlist installed.

**Comment by idpaterson** [comment]
Can you try signing out and back in via `wl-pref`? I'm not sure what might be the problem here since the workflow should now show any errors from the API in the notification...

**Comment by fabianvalkenberg** [comment]
How can you sign in / out via wl-pref? I dont have that option... 
![screenshot 2016-12-01 21 04 41](https://cloud.githubusercontent.com/assets/24301373/20810386/cf705c32-b809-11e6-8452-5485f9364ead.png)

**Comment by idpaterson** [comment]
Ah good, the missing account information in `wl-pref` is likely related to the issue with adding tasks. The workflow comes bundled with a few reset commands that will allow you to log out. Try `_wl-full-reset` which was added for cases like this where the workflow is not acting properly.

**Comment by fabianvalkenberg** [comment]
Excellent! this solves the issue. Many thanks!

**Comment by idpaterson** [comment]
Thank you for using the workflow, I'm glad to hear that it has worked well for you up to this point!

**Comment by idpaterson** [comment]
Oh and please let me know if it happens again especially with any regularity as that would be important to fix!
