### ISSUE TITLE
Keychain error when setup

### ISSUE THREAD

**Issue by Skakiz** [idpaterson/alfred-wunderlist-workflow#152]
Hi,
I'm new to alfred, wunderlist and Mac, wow... 😮 

When I should setup my "wl Please log in". I get a exception notification "Unknown Keychain error : security : SecKeychainItemCreateFromContent (<d"

How do I add a keychain? 
I have created an app in wunderlist. If i can use that... 
I have tried to install the wunderlist app. 

Im on High Sierra 10.13.3

Any suggestions?
Thanks!

**Comment by Skakiz** [comment]
Hi,
I found a solution, it seems to be a bug in High Sierra.

The fix:
Try opening Keychain Access.app. Right-click on the login keychain and try locking it and then unlocking it again.

Thanks!
//Andreas

**Comment by idpaterson** [comment]
Thanks for the update!
