### ISSUE TITLE
Improve task entry 

### ISSUE THREAD

**Issue by idpaterson** [idpaterson/alfred-wunderlist-workflow#49]
The primary feature for milestone 0.4, the first release using the official Wunderlist API, is an improved task entry experience. 

## A new focus

The workflow will focus on making functionality obvious and accessible while transforming new users into power users. The first few times you choose a list for a task you might use the menu, but if you read the prompt or pay attention to the text after doing so you'll soon learn that you can just type `auto: Oil change` to add an item to your *Automotive* list. 

An early preview:
![workflow preview](https://cloud.githubusercontent.com/assets/507058/6241002/68e29958-b6e4-11e4-8c08-af0c3739aa1f.png)

### New task-related features

The following basic features are much more accessible in the API than they were with UI automation.

#### Due dates

The datepicker in Wunderlist is not bad, but apps like Fantastical that use natural language processing to set dates are much more pleasurable to use. The workflow will allow setting due dates with just about any expression of a date. Set the due date to *tomorrow*, *next Tuesday*, *05/28*, *April*, *July 4*, etc.

##### `due` keyword may be required
There is some overhead involved in parsing the task for dates. It takes about 20ms on my 2011 MacBook Air, but that represents a 30% increase in the delay of the response for each keystroke on task entry. It is best to keep the script filters as lean as possible.

Some phrases like `next week` do not work with the `nlp()` function of `parsedatetime`. The benefit of `nlp()` is that it exposes information about the range of text that matched which allows the date text to be removed from the task. However, if it does not work with certain common phrases then it may be best to require "due" to appear at the end of the task and just remove any text that follows it. Of course if there are no dates represented in the text following due then the workflow will leave it as text.

This would be a bit of an annoyance since phrases like *Change oil filter next Tuesday* are more natural than *Change oil filter due next Tuesday*, so I may hold off on making "due" a requirement.

##### When a task ends in `due`
Show suggestions like *today*, *tomorrow*, and *next month*. Try to make it clear that the user can type any date they want. This will also serve as the submenu upon actioning the *Set a due date item.

##### When the workflow gets it wrong
If the task parses out to a date but it's not a due date, there should be a way to suppress that being handled as a due date. I'm not quite sure how to handle that yet.

#### Recurrence

Recurrence can be triggered with the `every` keyword plus a time unit `month`, `week`, or `day` and an optional number. For example, `every month`, `every 2 weeks`. The entire phrase will be removed from the final task text.

##### Due date is required
If a recurrence is specified without a due date, set the due date to today for the first occurrence.

An alternate form allows specifying the recurrence implicitly along with a due date.
* `every Monday` sets the due date to the next Monday with a weekly recurrence
* `every Feb 14` sets the due date to the next February 14 with an annual recurrence
* The monthly form, which might look something like `every 12th`, will not be supported because `parsedatetime` does not recognize that as a date.

##### When a task ends in `every`
Show suggestions like *week*, *month*, *year*, *3 months*. This will also serve as the submenu upon actioning the *Make it a recurring task* item.

##### More complex recurrence will not be implemented
The workflow could support more complicated recurrence that requires creating multiple tasks, but that will only be pursued if there is demand for such a thing. For example, `every March 1 and April 15` which would be set up as two separate tasks that repeat annually. 

#### Starred tasks

Starred tasks may not be the most useful feature, but they are easy to implement. End the task with an asterisk (*) and it's starred.

#### Select a list

Okay so it's not a new feature, but selecting a list will be retained. Prefix the task with a list name or portion of a list name, followed by a colon. The lists will be available by typing a colon at the beginning of a task or accessing the Select a List item.

## Previous behavior

The previous version of the workflow showed each of the lists when entering a task. The workflow was focused around getting tasks into lists, because there was not a whole lot more that could be done by interacting with the UI without a lot of legwork.

![Adding a task to Wunderlist](https://camo.githubusercontent.com/6f7ef85dab61414625632bba16283138a6484cdc/68747470733a2f2f7261772e6769746875622e636f6d2f69647061746572736f6e2f616c667265642d77756e6465726c6973742d776f726b666c6f772f67682d70616765732f696d616765732f73637265656e73686f74732f6164645f7461736b5f746f5f6c6973742e6a7067)

## Not in this release

The API exposes a lot of features that will eventually make it into the workflow, but not in the first API-supported release. These may be planned for future releases based on popular demand and suggestions for a good way to do them.

* Tag suggestions when you begin to type a #hashtag
** Tags are not actually part of the API, would require some post-processing after syncing data to a local db
* Reminders
* Subtasks
* Notes
* File attachments
* Comments
* Assignees
* Editing/moving/deleting an existing task
** Task search is not part of the API, would require syncing data to a local db

**Comment by idpaterson** [comment]
Sexy new icons throughout and improved context sensitivity... nearly time to package up a beta!

![screen shot 2015-02-21 at 10 13 02 pm](https://cloud.githubusercontent.com/assets/507058/6317245/e3751742-ba16-11e4-9d73-c9678f243956.png)

![screen shot 2015-02-21 at 10 14 29 pm](https://cloud.githubusercontent.com/assets/507058/6317252/07cb63c6-ba17-11e4-89a0-8a7271ebc24e.png)

![screen shot 2015-02-21 at 10 12 40 pm](https://cloud.githubusercontent.com/assets/507058/6317254/1fcea9ce-ba17-11e4-9955-dd3db83dfd26.png)

**Comment by idpaterson** [comment]
This is working well. Consideration may be needed in 0.5 for suppressing date or recurrence parsing on a specific task, but we'll see if anyone has issues with that first.

**Comment by felixbouleau** [comment]
I've noticed recently that I need to use the "due" keyword when adding due dates. Before, I didn't need to do that.

Did you decide to implement that after all? Is there a way for me to change it back?

(Thanks for this workflow, it saves me SO much time!)

**Comment by idpaterson** [comment]
Thanks for the comment, I'm not sure what might have happened but glad to hear it is working for you again!
