### ISSUE TITLE
Authorization Error – Can't Connect to Localhost

### ISSUE THREAD

**Issue by CalebGrove** [idpaterson/alfred-wunderlist-workflow#54]
I tried to use the just-released beta version, but I can't finish authorizing at it appears that the my computer can't connect to localhost:6200.

I'm afraid that all the information I have for now – any other information I can gather?

**Comment by idpaterson** [comment]
Thanks for trying it out! The workflow starts a single-request local web server to handle the authorization response from Wunderlist; let's try a few things:

1. What is your python version? `python --version` in Terminal
2. Open the Wunderlist workflow screen in Alfred and click the bug icon. Try to log in then copy the results in a reply on this thread
![screen shot 2015-03-13 at 8 20 35 am](https://cloud.githubusercontent.com/assets/507058/6638235/2cae343c-c95a-11e4-8886-dd2517579fe4.png)
3. If nothing there looks useful, right-click the workflow in Alfred's workflow list and select *Show in Finder*. Open a terminal to this directory then run `python alfred-wunderlist-workflow.py login --commit` and paste the result here.

Should be able to troubleshoot if we can get useful information from either 2 or 3 above.

**Comment by CalebGrove** [comment]
Ian,

Thanks!

1. Python 2.7.6

2. [Here's the output](https://gist.github.com/CalebGrove/20d7484cae5fffa31b0f), it does appear that there are two (maybe three) errors: [line 10](https://gist.github.com/CalebGrove/20d7484cae5fffa31b0f#file-errors-L10), [line 31](https://gist.github.com/CalebGrove/20d7484cae5fffa31b0f#file-errors-L31), and [line 53](https://gist.github.com/CalebGrove/20d7484cae5fffa31b0f#file-errors-L53).

3. [Here's the terminal output](https://gist.github.com/CalebGrove/57c15d3f65576afcfdea), it might be more helpful as it seems to have information regarding an exception that looks like it is related to the web server.

**Comment by idpaterson** [comment]
Perfect, that's what I needed! I forgot to bundle the python requests library.

**Comment by idpaterson** [comment]
Please try [this build](https://github.com/idpaterson/alfred-wunderlist-workflow/blob/develop/Wunderlist.alfredworkflow?raw=true), which now includes the missing dependency.

**Comment by CalebGrove** [comment]
I don't have time to really test the workflow, but the authorization worked! Thanks.

**Comment by idpaterson** [comment]
That's fine, thanks for finding and helping debug this one! The beta 1 release has been updated with a fixed workflow.
