### ISSUE TITLE
Error: Global name 'queryfile' not defined

### ISSUE THREAD

**Issue by iansoper** [idpaterson/alfred-wunderlist-workflow#59]
I get this error when adding a task via the workflow:
`workflow.py:1990 ERROR    global name 'queryfile' is not defined`

I tried clearing the workflow data folder and reinstalling, still getting this error. I'm using beta 2.

**Comment by idpaterson** [comment]
Ugh, a very obvious typo in my code. I'll update that right away, thanks for reporting!

**Comment by iansoper** [comment]
:+1: No problem!

**Comment by idpaterson** [comment]
Should be good to go now, sorry about that. The 0.4.0-beta.2 release was updated with [the fixed workflow](https://github.com/idpaterson/alfred-wunderlist-workflow/releases/download/0.4.0-beta.2/Wunderlist.alfredworkflow).
