### ISSUE TITLE
Old Download Link In Release

### ISSUE THREAD

**Issue by CalebGrove** [idpaterson/alfred-wunderlist-workflow#64]
Erm...the [download link](https://github.com/idpaterson/alfred-wunderlist-workflow/releases/download/0.4.0-beta.3/Wunderlist.alfredworkflow) for the [latest release](https://github.com/idpaterson/alfred-wunderlist-workflow/releases) downloads the old version of the workflow. You might want to fix this. :)

**Comment by idpaterson** [comment]
Oh my, *that* old version... Maybe some day I will be able to work on this in the daytime and avoid stupid mistakes like that!

It should be correct now, oops!
