### ISSUE TITLE
Option to always set a reminder

### ISSUE THREAD

**Issue by idpaterson** [idpaterson/alfred-wunderlist-workflow#65]
While I only use reminders in limited circumstances, the Wunderlist mobile app seems to automatically set a reminder at 9:00 AM with any due date added in quick entry mode. I don't care for that personally but others may find it useful.

The option would need to allow selection of the reminder relative to the due date.

If anyone would like to see this feature realized in a future version of the workflow please comment on this issue.

**Comment by idpaterson** [comment]
The Wunderlist app seems to be doing this now, whenever I create a task with a due date it sets a reminder. Unfortunately it is setting reminders for the following day, which is weird... Personally I don't like automatic reminders and end up removing them, but the integration in the Wunderlist app suggests that some people might want this feature.

**Comment by danilo-barboza** [comment]
:+1:

**Comment by idpaterson** [comment]
Was just thinking about this again yesterday. Awhile after finding this behavior I found a Wunderlist account preference that controlled it (*General > Enable auto reminders*). I disabled it because I prefer to reduce reminders to only the most critical due dates, but I'm sure there are many people who enjoy that.

I just found an undocumented settings route on the Wunderlist API that provides this value for the current user, which would allow the workflow to just "do the right thing" based on the user's preference. I think this sounds like a great improvement to reminders for a version 0.5.1. 

I will use a test account with Wunderlist to see if I can allow the workflow to change that preference as well. Currently I am afraid of breaking my account since the settings API is undocumented.

**Comment by idpaterson** [comment]
@danilo-barboza would you give [this preview](https://github.com/idpaterson/alfred-wunderlist-workflow/raw/feature/auto-reminder/Wunderlist.alfredworkflow) a try for me, please? I added an option in Preferences that allows you to automatically set a reminder for any task with a due date. You may need to log out then back in to the workflow, but by default it should match your Wunderlist preference. Of course, if your entry includes a different reminder that will override the default.

Once set you can toggle the preference in the workflow (at least for now changing the setting in the workflow will not affect your preference in Wunderlist). It will not stay in sync with the setting in Wunderlist in case some people find it useful to have different behavior.

**Comment by danilo-barboza** [comment]
I just used the preview and it works great! I used "wl Personal: Test new preview version of workflow plugin today". ;)

I just found something that is a little bit different from the Wunderlist App itself: Whenever I set the due to "today" the app will not set the reminder to 9AM, it will, instead, set a reminder to "current time + 1 hour". I kind of like that in the App and it will be nice to have this in the workflow as well. Specially for those  looking for a better alternative to the app itself.

Thanks for putting this together!

**Comment by idpaterson** [comment]
Ahh good observation, I'll do the same!

**Comment by idpaterson** [comment]
It seems to "round up" as well, adding a task at 7:48AM sets a reminder at 8:50AM.

**Comment by idpaterson** [comment]
[This update](https://github.com/idpaterson/alfred-wunderlist-workflow/raw/feature/auto-reminder/Wunderlist.alfredworkflow) now mimics the rounding behavior of Wunderlist with a preference that allows you to either

1. Use the default 1 hour offset that Wunderlist 
2. Set any offset you want (e.g. 30 minutes, 1h 30m, 123 minutes...)
3. Disable the offset and always use the default reminder time (even if it has passed that time today)

With regard to the third option, it currently still allows you to set reminders in the past. If it is 10:00AM and your default reminder is 9:00AM it will set the reminder to 9:00AM which is not *customarily* helpful. An alternative would be to use the default reminder time unless it has already passed in which case set a reminder (1 hour probably). That seems like the right thing to do but the rules get pretty complex and it might be best to stick with the simple behavior. Since parsedatetime is utter magic you can always do something like "r 30m" to set a reminder 30 minutes from now so I don't think the extra complexity is justified – either offset the reminder time when due today or don't.

**Comment by danilo-barboza** [comment]
Awesome!

I just tested it here and it's working great! I love the way we can see the reminder time in the suggestion option.

I totally agree with you that it may not be worth adding the complexity to check the current date to adjust the default reminder time.

I did some pretty basic testing but I believe it's totally worth a new release!

**Comment by idpaterson** [comment]
Agreed. You caught me on a particularly good weekend to get some work done :)
