### ISSUE TITLE
"in" keyword for list assignment

### ISSUE THREAD

**Issue by idpaterson** [idpaterson/alfred-wunderlist-workflow#67]
While using the workflow I found that having to prefix the list is a bit of a stumbling block. It's easy to type a substring of the list name followed by a colon, but I have to *think* about it before creating my task, which can distract me from the task itself.

An "in list name" keyword (required to be at the end of the query to simplify matching) would be more convenient for me. I can add it at the end after typing the task. If this is added, the list menu should probably still use the prefix syntax since it is more reliable to parse.

If the query ends in "in" followed by something that does not match a list it would remain as normal text in the task.

**Comment by idpaterson** [comment]
"in" is also a keyword for date parsing (e.g. *in a month*) so this will need to be parsed out *before* looking at dates and of course only if a list name matches.

**Comment by idpaterson** [comment]
This new syntax has been added and can be tested [here](https://github.com/idpaterson/alfred-wunderlist-workflow/raw/feature/infix-list-title/Wunderlist.alfredworkflow). Here are the basic rules:

1. Use the "in" or "in list" keyword followed by a list name or portion of a list name.
2. Use at least 3 letters to reference the list, or if using 1-2 letters make them all-caps (this should help avoid false positives, e.g. "in a" is ignored but "in A" will match your first list starting with/containing "a")
3. The "in" keyword will not work within your task title (e.g. "buy in Groceries milk" where the title would be "buy milk"), but you may use it when followed by due, recurrence, or reminder phrases that will get parsed out of the task title (e.g. "buy milk tomorrow in Groceries every week remind me at noon")

**Comment by danilo-barboza** [comment]
I just tested this too and it's great!

I felt that it was a little bit weird to select the list to put my tasks on with the other format (eg. "wl Groceries: buy milk") and this feature makes it way more natural to me.

I can't wait to have 0.5.1 release with this feature and the one described on #65!

Thanks for working on these features! :+1:
