### ISSUE TITLE
Login can fail if local server address is aleady in use

### ISSUE THREAD

**Issue by idpaterson** [idpaterson/alfred-wunderlist-workflow#70]
Sometimes when I test logout and login too rapidly the server that listens for Wunderlist's redirect fails to start with an error about the port already being in use. This could also occur on any computer that is already listening on the port that the workflow uses.

**Comment by shahzeb1** [comment]
I still had this issue. I fixed it by manually changing the port in the URL. I changed it from `http://localhost/?state=...&code=...` to `http://localhost:6200/?state=...&code=...`

**Comment by idpaterson** [comment]
So after logging in with Wunderlist you were redirected to localhost without a port specified? That is odd, the redirect URL requested by the workflow includes :6200 and that is still set as the callback in the API side config...

I will take a look today to see if something has changed in how they do that redirect after login.

**Comment by shahzeb1** [comment]
That's correct. For some reason, port `:6200` was missing after I authorized Wunderlist access. I had to manually go into the folder and look at the python source code to figure out what could be going on there.

**Comment by Bergrebell** [comment]
same here!

**Comment by idpaterson** [comment]
I tried this with different callback URLs and it seems that Wunderlist has begun stripping off the port defined in my API settings. The callback URL specified in the workflow has to match the URL specified at developer.wunderlist.com, which it does, but at some point the port is getting clobbered.

I opened issue #82 to track this specific problem. Thank you for reporting!

**Comment by idpaterson** [comment]
This would be nice to fix, but it is on hold until the Wunderlist API supports a variable localhost port for the authentication callback. I have submitted [a request for this](https://github.com/wunderlist/api/issues/12) citing the allowance of any localhost port by Google login as precedent. 

It would be possible to work around the issue by directing the authentication callback to a remote site like http://idpaterson.github.io/alfred-wunderlist-workflow/ which could then try various localhost ports, but that is both less secure and more prone to causing undefined behavior in the applications that are using the unavailable ports. I don't think that routing authentication through a middleman like this (which would have to be done for everyone regardless of whether the port is open since only one callback URL is allowed) is a justifiable compromise in order to fix a fairly niche issue.

**Comment by idpaterson** [comment]
I thought of and implemented a different workaround today. As of version 0.5.2 you can login by pasting the authorization URL into Alfred if the local server does not handle it.
