### ISSUE TITLE
Set reminder from a title

### ISSUE THREAD

**Issue by lvarayut** [idpaterson/alfred-wunderlist-workflow#84]
In Wunderlist, we could write `Do something at 10AM tomorrow`, it will automatically set a reminder at 10AM. I tried the same thing using this plugin. However, it didn't seem to work. Any workaround on this feature or do you have any plan to support it? BTW, Thanks for the great workflow!!

**Comment by idpaterson** [comment]
Excellent suggestion, the building blocks to allow this actually fell into place recently when parsedatetime was updated to improve differentiation between dates with and without a time component. This is the last bit of syntax that I would like to support before releasing version 0.5.

For now, please [download](https://github.com/idpaterson/alfred-wunderlist-workflow/releases/tag/0.5.0-beta.2) the beta version of 0.5.0 which includes support for reminders. There is a bit more info on how to use the reminders feature [here](https://github.com/idpaterson/alfred-wunderlist-workflow/releases/tag/0.5.0-beta.1).

The syntax is a bit different, you can say "remind me," "reminder," "alarm," or simply "r" followed by the reminder date and/or time.
![screen shot 2015-12-02 at 9 13 14 am](https://cloud.githubusercontent.com/assets/507058/11533023/86b7a62a-98d5-11e5-8450-99b96ff9c725.png)

**Comment by lvarayut** [comment]
Thanks @idpaterson. This is really really useful feature!! I just tried it and it worked like a charm!  :)

**Comment by idpaterson** [comment]
Thanks, the release has been held up for a long time but I hope to have a final 0.5.0 out soon so that people who haven't visited GitHub to download the beta will get the automatic update prompt in their workflow.

**Comment by idpaterson** [comment]
[Version 0.5.0](https://github.com/idpaterson/alfred-wunderlist-workflow/releases/edit/0.5.0) has been released with support for the time + date format. Your workflow should show a prompt to update to 0.5.0 the next time you use it. Thanks again for the idea!

**Comment by lvarayut** [comment]
That's perfect. Thanks so much!
