### ISSUE TITLE
Relevance of this workflow

### ISSUE THREAD

**Issue by idpaterson** [idpaterson/alfred-wunderlist-workflow#85]
Just a quick poll, I want your feedback!

It has been great to see many of the features in this workflow make their way into Wunderlist itself over the past few months. As Wunderlist continues to improve keyboard accessibility and natural language text processing, have you started using the Wunderlist app more than the workflow, or is there still inherent value in having access to Wunderlist within Alfred even if Wunderlist itself became just as efficient to use? What would you most like to see in the workflow?

**Comment by ckoeberle** [comment]
I really love this workflow and it simplifies my daily work. I guess I use it 10-20 times a day, so for me it's absolutely relevant!!!
Thank you for your great work, keep it up please

**Comment by danilo-barboza** [comment]
I just bought the Alfred Powerpack because of this workflow! I've been using the default Wunderlist for Mac for more than a month and I miss some stuff. So this is definitely relevant.

I just miss the ability to search my tasks and mark them as done directly from Alfred. I just ended up here looking for a way to do that, by the way.

Comparing to the features in the Wunderlist app itself, this workflow is way more powerful. I know a little bit of Python and JS, I'll take a look once I have some spare time to see if I'm able to send some pull request. ;)

Thanks for building this workflow, it's a great piece of work. I love the README as well, very helpful and well organized! :+1:

**Comment by idpaterson** [comment]
@danilo-barboza and @ckoeberle  that's great! Thanks for the kind words. 

Task searching and hashtag completion are implemented in [a feature branch](https://github.com/idpaterson/alfred-wunderlist-workflow/tree/feature/task-sync) but the sync is currently still non-parallelized and therefore too slow to be worthy of a beta release. The Wunderlist API has an interesting structure which is helpful in some cases but pretty much makes it necessary to sync everything (e.g. no API to search tasks).

Anyway, I would love to add task searching and completion soon, my particular favorite benefit over Wunderlist being #79 where a task could be completed and marked due today so that the next occurrence is relative to today rather than the original due date. I'm frequently missing my non-critical due dates and very often set things due today before completing. For example, if I was supposed to water a plant two days ago, repeating every 3 days, I certainly don't need to water it today then again tomorrow, the next due date would instead be 3 days from today. I would love to just hold a modifier key in Alfred like Shift or Cmd when completing the task to make that happen.

**Comment by idpaterson** [comment]
Just a quick update on task searching and hashtags... I made the sync process concurrent where possible bringing the total sync time for my account down from 2 1/2 minutes to 13 seconds. Subsequent syncs (unless you have made big changes to multiple list since the last sync) are around 5 seconds. That's definitely fast enough for beta testing!

I'm going to do some testing to make sure everything updates properly in the workflow when changed externally, just wanted to share the news. Before the next beta release I need to make a dedicated route to search tasks to avoid conflicts with the current task entry process. For now I am showing matches while adding tasks which may or may not be the best way to handle task searching. I fear that it may reduce the responsiveness of task entry depending on how many tasks you have, so for now I will err on the side of a more explicit search interface.
