### ISSUE TITLE
Task searching feature requests

### ISSUE THREAD

**Issue by idpaterson** [idpaterson/alfred-wunderlist-workflow#95]
> If you have not yet downloaded [version 0.6.0-alpha.1](https://github.com/idpaterson/alfred-wunderlist-workflow/releases/tag/0.6.0-alpha.1), please consider doing so if you would like to help test the next big update to the workflow. 

The workflow includes a screen for searching tasks that allows you to search your tasks by hashtag or keyword. 

![search](https://cloud.githubusercontent.com/assets/507058/13110488/60d4dc38-d54e-11e5-9c16-6ecb3f987795.png)

I would like feedback on a few things:

- **Are there any other fields that you would like to search by?** For example, all monthly recurring tasks or all starred tasks.
- **Is it necessary to search completed tasks?** Similar to the Sort option at the bottom of the Due screen I could add a row at the bottom of search results to toggle completed tasks. 

I am considering passing the search term through the task parser then applying filters based on the result (list, recurrence, due date, starred). There are some limitations there like no syntax to negate a filter, but it might not matter.

**Comment by kaspersoerensen** [comment]
This is a great idea! I have tested the 0.6.0-alpha version, but quite often a get this error:

![skaermbillede 2016-03-11 kl 12 36 36](https://cloud.githubusercontent.com/assets/2018894/13701146/2767b8e0-e786-11e5-8b90-00337ca1a595.png)

**Comment by idpaterson** [comment]
@kaspersoerensen, would you please check which alpha version of the workflow you have at `wl:about`? If you do not have the latest (0.6.0-alpha.5) first please try updating [here](https://github.com/idpaterson/alfred-wunderlist-workflow/releases/tag/0.6.0-alpha.5). Otherwise if you are on the latest version, please try signing out and back into the workflow with `wl:logout`. This will reset the database that stores your tasks. It looks like this could be an issue with upgrading from an older version of the workflow.

**Comment by kaspersoerensen** [comment]
Perfect - logging out and back in fixed it. And then I also updated to alpha.5

**Comment by idpaterson** [comment]
Good, there may be minor database changes in future alpha updates that cause similar behavior - if anyone is reading this in the future just try signing out and back in. Updates from 0.5.x will be properly migrated when 0.6.0 is installed to avoid logging out and I will try to add migration for any major changes in future 0.6.0-x.x pre-releases.

**Comment by csteinlehner** [comment]
I can't find the 'due-search' where can I find it?

**Comment by idpaterson** [comment]
There should be a `wl-due` and `wl-search`. You can search your due tasks on the due screen and you can search or browse all of your tasks from the search screen. You can navigate to these pages and others from the `wl` welcome screen until you've learned the commands well enough to type them directly.

**Comment by csteinlehner** [comment]
Ah, now I get it. I thought it is something like the today / week view like in the wunderlist app. But I just see what is due today, right?

**Comment by idpaterson** [comment]
That's right, just what is due or overdue, like the Today smart list in Wunderlist. I haven't added an upcoming tasks screen yet; working through some sync problems first.

**Comment by idpaterson** [comment]
A list of upcoming tasks was added in the latest beta release.
